import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult, setPersistence, browserLocalPersistence, signOut, signInWithCredential } from 'firebase/auth';
import { getFirestore, collection, doc, setDoc, getDoc, onSnapshot, query, where, orderBy, getDocFromServer } from 'firebase/firestore';
import { Capacitor } from '@capacitor/core';
import { App as CapacitorApp } from '@capacitor/app';
import { Browser } from '@capacitor/browser';

// This file will be generated by set_up_firebase
import firebaseConfig from './firebase-applet-config.json';

const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
setPersistence(auth, browserLocalPersistence);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
export { collection, doc, setDoc, getDoc, onSnapshot, query, where, orderBy, getDocFromServer };
export const googleProvider = new GoogleAuthProvider();
googleProvider.setCustomParameters({ prompt: 'select_account' });

const GOOGLE_SCOPES = [
  'https://www.googleapis.com/auth/classroom.courses.readonly',
  'https://www.googleapis.com/auth/classroom.announcements.readonly',
  'https://www.googleapis.com/auth/classroom.coursework.me.readonly',
  'https://www.googleapis.com/auth/classroom.coursework.me',
  'https://www.googleapis.com/auth/classroom.coursework.students.readonly',
  'https://www.googleapis.com/auth/classroom.student-submissions.me.readonly',
  'https://www.googleapis.com/auth/classroom.student-submissions.students.readonly',
  'https://www.googleapis.com/auth/classroom.rosters.readonly',
  'https://www.googleapis.com/auth/tasks',
  'https://www.googleapis.com/auth/calendar'
];

// Add Classroom and Tasks scopes
GOOGLE_SCOPES.forEach(scope => googleProvider.addScope(scope));

export const isNativeApp = () => Capacitor.isNativePlatform();

export const isBlockedInAppBrowser = () => {
  if (isNativeApp()) return false;

  const ua = navigator.userAgent || '';
  const blockedBrowsers = [
    'FBAN',
    'FBAV',
    'Instagram',
    'Line/',
    'TikTok',
    'Twitter',
    'Snapchat',
    'Pinterest',
    'LinkedInApp'
  ];

  return blockedBrowsers.some(browser => ua.includes(browser));
};

// Listen to customized deep link auth intent inside capacitor
if (isNativeApp()) {
  CapacitorApp.addListener('appUrlOpen', async (event) => {
    if (event.url.includes('br.com.jefson.tarefaflow://auth')) {
      Browser.close().catch(() => {});
      const url = new URL(event.url);
      const idToken = url.searchParams.get('id_token') || url.searchParams.get('idToken');
      const accessToken = url.searchParams.get('access_token') || url.searchParams.get('accessToken');
      
      if (idToken) {
        try {
          const credential = GoogleAuthProvider.credential(idToken, accessToken || undefined);
          const authResult = await signInWithCredential(auth, credential);
          localStorage.setItem('tarefaflow_native_login_in_progress', '0');
          window.dispatchEvent(new CustomEvent('google-access-token-updated', {
            detail: {
              user: authResult.user,
              accessToken: accessToken,
            }
          }));
        } catch (error) {
          console.error("Deep link auth error:", error);
          localStorage.setItem('tarefaflow_native_login_in_progress', '0');
        }
      }
    }
  });
}

export const signIn = async () => {
  try {
    if (isNativeApp()) {
      localStorage.setItem('tarefaflow_native_login_in_progress', '1');
      const loginUrl = `https://${firebaseConfig.authDomain}?source=android-login`;
      await Browser.open({ url: loginUrl, windowName: '_system' });
      return { user: null, accessToken: null };
    }

    const result = await signInWithPopup(auth, googleProvider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    return { user: result.user, accessToken: credential?.accessToken };
  } catch (error: any) {
    console.error("Popup auth failed:", error);
    if (error.code === 'auth/popup-blocked' || (error.message && error.message.includes('popup'))) {
      console.warn("Popup blocked, falling back to signInWithRedirect...");
      await signInWithRedirect(auth, googleProvider);
      return { user: null, accessToken: null };
    }
    throw error;
  }
};

export const logout = async () => {
  return signOut(auth);
};

export const handleRedirectResult = async () => {
  try {
    const result = await getRedirectResult(auth);
    if (result) {
      const credential = GoogleAuthProvider.credentialFromResult(result);
      return { user: result.user, accessToken: credential?.accessToken };
    }
  } catch (error: any) {
    console.error("Error in getRedirectResult:", error);
    if (error.code === 'auth/missing-initial-state' || (error.message && error.message.includes('missing initial state'))) {
      console.warn("Ignored getRedirectResult error due to browser environment constraints.");
      return null;
    }
    throw error;
  }
  return null;
};
