import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult, setPersistence, browserLocalPersistence, signOut, signInWithCredential } from 'firebase/auth';
import { getFirestore, collection, doc, setDoc, getDoc, onSnapshot, query, where, orderBy, getDocFromServer } from 'firebase/firestore';
import { Capacitor } from '@capacitor/core';
import { Browser } from '@capacitor/browser';
import { App } from '@capacitor/app';

// This file will be generated by set_up_firebase
import firebaseConfig from './firebase-applet-config.json';

const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
setPersistence(auth, browserLocalPersistence);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
export { collection, doc, setDoc, getDoc, onSnapshot, query, where, orderBy, getDocFromServer };
export const googleProvider = new GoogleAuthProvider();
googleProvider.setCustomParameters({ prompt: 'select_account' });

const GOOGLE_SCOPES = [
  'https://www.googleapis.com/auth/classroom.courses.readonly',
  'https://www.googleapis.com/auth/classroom.announcements.readonly',
  'https://www.googleapis.com/auth/classroom.coursework.me.readonly',
  'https://www.googleapis.com/auth/classroom.coursework.me',
  'https://www.googleapis.com/auth/classroom.coursework.students.readonly',
  'https://www.googleapis.com/auth/classroom.student-submissions.me.readonly',
  'https://www.googleapis.com/auth/classroom.student-submissions.students.readonly',
  'https://www.googleapis.com/auth/classroom.rosters.readonly',
  'https://www.googleapis.com/auth/tasks',
  'https://www.googleapis.com/auth/calendar'
];

GOOGLE_SCOPES.forEach(scope => googleProvider.addScope(scope));

const ANDROID_LOGIN_SOURCE = 'android-login';
const ANDROID_CALLBACK_SCHEME = 'br.com.jefson.tarefaflow';
const WEB_LOGIN_ORIGIN = 'https://tarefaflow2.vercel.app';

export const isNativeApp = () => Capacitor.isNativePlatform();

export const isBlockedInAppBrowser = () => {
  if (isNativeApp()) return false;

  const ua = navigator.userAgent || '';
  const blockedBrowsers = [
    'FBAN',
    'FBAV',
    'Instagram',
    'Line/',
    'TikTok',
    'Twitter',
    'Snapchat',
    'Pinterest',
    'LinkedInApp'
  ];

  return blockedBrowsers.some(browser => ua.includes(browser));
};

const isAndroidLoginBridge = () => {
  try {
    return new URLSearchParams(window.location.search).get('source') === ANDROID_LOGIN_SOURCE;
  } catch {
    return false;
  }
};

const buildExternalLoginUrl = () => `${WEB_LOGIN_ORIGIN}/?source=${ANDROID_LOGIN_SOURCE}`;

const buildAndroidCallbackUrl = (idToken?: string | null, accessToken?: string | null) => {
  const params = new URLSearchParams();
  if (idToken) params.set('id_token', idToken);
  if (accessToken) params.set('access_token', accessToken);
  params.set('source', ANDROID_LOGIN_SOURCE);
  return `${ANDROID_CALLBACK_SCHEME}://auth#${params.toString()}`;
};

const parseCallbackTokens = (url: string) => {
  const raw = url.includes('#') ? url.split('#')[1] : url.split('?')[1];
  const params = new URLSearchParams(raw || '');
  return {
    idToken: params.get('id_token'),
    accessToken: params.get('access_token'),
    source: params.get('source')
  };
};

export const handleNativeAuthCallbackUrl = async (url: string) => {
  if (!url.startsWith(`${ANDROID_CALLBACK_SCHEME}://`)) return null;

  const { idToken, accessToken, source } = parseCallbackTokens(url);
  if (source !== ANDROID_LOGIN_SOURCE || !idToken) return null;

  const credential = GoogleAuthProvider.credential(idToken, accessToken || undefined);
  const authResult = await signInWithCredential(auth, credential);

  if (accessToken) {
    localStorage.setItem('google_access_token', accessToken);
  }

  try {
    await Browser.close();
  } catch {
    // Browser.close may fail if the system browser was already closed.
  }

  window.dispatchEvent(new CustomEvent('google-access-token-updated', { detail: { accessToken } }));
  return { user: authResult.user, accessToken };
};

if (Capacitor.isNativePlatform()) {
  App.addListener('appUrlOpen', async ({ url }) => {
    try {
      const result = await handleNativeAuthCallbackUrl(url);
      if (result) {
        window.location.reload();
      }
    } catch (error) {
      console.error('Native auth callback failed:', error);
    }
  });
}

export const signIn = async () => {
  try {
    if (isNativeApp()) {
      await Browser.open({ url: buildExternalLoginUrl(), presentationStyle: 'fullscreen' });
      return { user: null, accessToken: null };
    }

    const result = await signInWithPopup(auth, googleProvider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    const accessToken = credential?.accessToken;
    const idToken = credential?.idToken || await result.user.getIdToken();

    if (accessToken) {
      localStorage.setItem('google_access_token', accessToken);
    }

    if (isAndroidLoginBridge()) {
      window.location.href = buildAndroidCallbackUrl(idToken, accessToken);
      return { user: result.user, accessToken };
    }

    return { user: result.user, accessToken };
  } catch (error: any) {
    console.error('Google auth failed:', error);
    if (!isNativeApp() && (error.code === 'auth/popup-blocked' || (error.message && error.message.includes('popup')))) {
      console.warn('Popup blocked, falling back to signInWithRedirect...');
      await signInWithRedirect(auth, googleProvider);
      return { user: null, accessToken: null };
    }
    throw error;
  }
};

export const logout = () => signOut(auth);

export const handleRedirectResult = async () => {
  try {
    const result = await getRedirectResult(auth);
    if (result) {
      const credential = GoogleAuthProvider.credentialFromResult(result);
      const accessToken = credential?.accessToken;
      const idToken = credential?.idToken || await result.user.getIdToken();

      if (accessToken) {
        localStorage.setItem('google_access_token', accessToken);
      }

      if (isAndroidLoginBridge()) {
        window.location.href = buildAndroidCallbackUrl(idToken, accessToken);
      }

      return { user: result.user, accessToken };
    }
  } catch (error: any) {
    console.error('Error in getRedirectResult:', error);
    if (error.code === 'auth/missing-initial-state' || (error.message && error.message.includes('missing initial state'))) {
      console.warn('Ignored getRedirectResult error due to browser environment constraints.');
      return null;
    }
    throw error;
  }
  return null;
};
